export const KEYWORD_PHOTOS_SUCCESS = "KEYWORD_PHOTOS_SUCCESS";
export const KEYWORD_PHOTOS_FAILURE = "KEYWORD_PHOTOS_FAILURE";
export const KEYWORD_VIDEOS_SUCCESS = "KEYWORD_VIDEOS_SUCCESS";
export const KEYWORD_VIDEOS_FAILURE = "KEYWORD_VIDEOS_FAILURE";